@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Nikolas",
  "email": "nikolas@email.com",
  "password": "54321"
}

###
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "nikolas@email.com",
  "password": "54321"
}

###
# @name upload_image
POST {{baseUrl}}/images
Content-Type: application/json
Authorization: Bearer {{authToken}}